name: Makefile CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v3

    - name: Dir
      run: make dir

    - name: Bootstrap
      run: make bootstrap

    - name: Build
      run: make build
